// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxyngdiehpsaublqlnkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4eW5nZGllaHBzYXVibHFsbmtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjI2OTAsImV4cCI6MjA2ODU5ODY5MH0.wMV1i1AN5b6w__b_e-eDrdztqRVcBrnYGtiRJLInJGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});